import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Sidebar from "./_components/sidebar";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Instagram Clone",
  description: "Generated by create next app",
};

export default function DashBoardLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main className="flex h-screen flex-col md:flex-row md:overflow-hidden">
      <div className="w-20 flex-none lg:w-64 md:border-r">
        <Sidebar />
      </div>

      <div className="flex-grow mx-auto mt-12 lg:mr-48 md:mt-0 sm:p-6 md:p-12 max-w-7xl flex-1 w-full overflow-y-auto">
        {children}
      </div>
    </main>
  );
}
